### ISSUE TITLE
`min_date` is ignored when navigating years forward then backward.

### ISSUE THREAD

**Issue by ssrebelious** [artembakhanov/python-telegram-bot-calendar#5]
User may enter date earlier than `min_date` if navigates forward in year menu, than backward.
Min date is set to year 2021, user can't choose year 2020 or earlier.
![image](https://user-images.githubusercontent.com/2326764/107081456-c4bf6400-6803-11eb-8519-98ea8c5eb238.png)
Move forward in menu
![image](https://user-images.githubusercontent.com/2326764/107081473-cc7f0880-6803-11eb-8cd6-9fcb877ea44f.png)
Move backward in menu: now dates prior 2021 are available:
![image](https://user-images.githubusercontent.com/2326764/107081497-d4d74380-6803-11eb-9220-84da590050b2.png)

**Comment by artembakhanov** [comment]
Hello! Thank you for the message. I could not repeat this. Can you please provide an example of code where `min_date` does not work properly?

For now, I can only say that you might have not specified `min_date` when creating a calendar object inside a query handler.
You need to pass all the arguments every time you create a calendar.

```
@bot.message_handler(commands=['start'])
def start(m):
    calendar, step = DetailedTelegramCalendar(min_date=date.today()).build()
    bot.send_message(m.chat.id,
                     f"Select {LSTEP[step]}",
                     reply_markup=calendar)


@bot.callback_query_handler(func=DetailedTelegramCalendar.func())
def cal(c):
    result, key, step = DetailedTelegramCalendar(min_date=date.today()).process(c.data)
    if not result and key:
        bot.edit_message_text(f"Select {LSTEP[step]}",
                              c.message.chat.id,
                              c.message.message_id,
                              reply_markup=key)
    elif result:
        bot.edit_message_text(f"You selected {result}",
                              c.message.chat.id,
                              c.message.message_id)
```

**Comment by ssrebelious** [comment]
Thanks, indeed I haven't specified min_date in the query handler. 

Is there a way to setup calendar with dynamic min and max dates in a DRY way?

**Comment by ssrebelious** [comment]
Посмотрел ваш профиль) Привет из Центра геоинформационных систем УИ  :wave:

**Comment by artembakhanov** [comment]
> Is there a way to setup calendar with dynamic min and max dates in a DRY way?
The module does not support it. But the easiest way that comes to my mind is to create a function that will create a calendar object, so you will need to call the function twice.
If you have any ideas how I can improve it I will be happy to see them:)


> Посмотрел ваш профиль) Привет из Центра геоинформационных систем УИ 👋
Привет👋  Приятно видеть людей из УИ)

**Comment by artembakhanov** [comment]
Feel free to reopen this issue
