### ISSUE TITLE
How can I remove year 2020 and start from 2021 onwards?

### ISSUE THREAD

**Issue by geraldspacelim** [artembakhanov/python-telegram-bot-calendar#7]

**Comment by makaramkd** [comment]
@geraldspacelim Look at this [example](https://github.com/artembakhanov/python-telegram-bot-calendar/blob/master/examples/date_ranges.py), you can set `min_date`.

**Comment by geraldspacelim** [comment]
@makaramkd thanks! however im looking at starting the year at 2021 then 2022... instead of starting at 2020. Also, is there a way that i can start off in the month selection instead of the year?

**Comment by artembakhanov** [comment]
@geraldspacelim

> however im looking at starting the year at 2021 then 2022... instead of starting at 2020

I still do not understand why can't you specify `min_date=date(year=2021)`?

> Also, is there a way that i can start off in the month selection instead of the year?

Do you want to exclude some month options from the selection? For example, each year you want it to be from June?

**Comment by artembakhanov** [comment]
Closing the issue because of lack of activity. Feel free to reopen it.
